overview:
  title: Kitchen Configurator
  image: logo.png
  description: Simple Room Configurator with 6 Layers.
  facts:
    - Object movement
    - Object colorization
    - Object visibility
  order: 3
schema: bootstrap-taupe
sample:
  menu:
    data: Furniture-menu.yml
  footer:
    credits:
      viewer:
        link: https://www.neptunelabs.com/fsi-layers/
  fsi:
    layers: true
  bootstrap:
    icons: true
  jquery:
    ui: true
