title: Kitchen Configurator
image: logo.png
description: Simple Room Configurator with 6 Layers.
facts:
  - Object movement
  - Object colorization
  - Object visibility
priority: 3
jsfiddle:
  mapping:
    html: "index.html"
    js: "kitchen.js"
    css: "kitchen.css"
  resources:
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/layers/js/fsilayers.js"
