title: Kitchen Configurator
image: logo.png
description: Simple Room Configurator with 6 Layers.
facts:
  - Object movement
  - Object colorization
  - Object visibility
priority: 3
jsfiddle:
  mapping:
    html: "index.html"
    js: "kitchen.js"
    css: "kitchen.css"
  resources:
    - https://cdn.jsdelivr.net/npm/bootstrap@$BOOTSTRAP_VERSION$/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@$BOOTSTRAP_VERSION$/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css
    - $FSI_SERVER$/$FSI_CONTEXT$/viewer/applications/layers/js/fsilayers.js
  tags:
    - FSI
    - FSI Server
    - FSI Layers
    - NeptuneLabs
