overview:
  title: Kitchen Configurator
  image: logo.png
  description: Simple Room Configurator with 6 Layers.
  facts:
    - Object movement
    - Object colorization
    - Object visibility
  order: 3
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/furniture-menu.yml
      footer:
          viewer:
            link: https://www.neptunelabs.com/fsi-layers/
      fsi:
        layers: true
      bootstrap:
        icons: true
      jquery:
        ui: true
  mapping:
    html: 'index.html'
    js: 'script.js'
    css: 'style.css'
playground:
  deploy: true
