title: Trains
image: logo.png
description: Multiple images are rendered and moved as parallax.
facts:
  - Object movement
  - Object rotation
  - Reference Sizing
priority: 2
jsfiddle:
  mapping:
    html: "index.html"
    js: "trains.js"
    css: "trains.css"
  resources:
    - $DEMO_FSI_SERVER$/viewer/applications/layers/js/fsilayers.js
  tags:
    - FSI
    - FSI Server
    - FSI Layers
    - NeptuneLabs
