overview:
  title: Trains
  image: logo.png
  description: Multiple images are rendered and moved as parallax.
  facts:
    - Object movement
    - Object rotation
    - Reference Sizing
  order: 5
sample:
  template:
    schema: framework-2023
    components:
      fsi:
        layers: true
  mapping:
    html: "index.html"
    js: "trains.js"
    css: "trains.css"
jsfiddle:
  deploy: true
