overview:
  title: Product Detail Page (PDP)
  image: logo.png
  description: PDP with Layers build from JSON.
  facts:
    - JS built FSI Layers
    - Object visibility
    - 575 combinations
  order: 4
schema: bootstrap-taupe
sample:
  menu:
    data: misc-menu.yml
  footer:
    viewer:
      link: https://www.neptunelabs.com/fsi-layers/
  fsi:
    layers: true
  bootstrap:
    icons: true
