overview:
  title: Product Detail Page
  image: logo.png
  description: PDP with Layers build from JSON.
  facts:
    - JS built FSI Layers
    - Object visibility
    - 575 combinations
  order: 4
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      highlight: DEAL OF THE DAY
      footer:
        viewer:
          link: https://www.neptunelabs.com/fsi-layers/
      fsi:
        layers: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
jsfiddle:
  deploy: true
