title: Product Detail Page
image: logo.png
description: PDP with Layers build from JSON.
facts:
  - JS built FSI Layers
  - Object visibility
  - 575 combinations
priority: 4
jsfiddle:
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
  resources:
    - https://cdn.jsdelivr.net/npm/bootstrap@$BOOTSTRAP_VERSION$/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@$BOOTSTRAP_VERSION$/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@$BOOTSTRAP_ICON_VERSION$/font/bootstrap-icons.css
    - $FSI_SERVER$/$FSI_CONTEXT$/viewer/applications/layers/js/fsilayers.js
  tags:
    - FSI
    - FSI Server
    - FSI Layers
    - NeptuneLabs
