title: Flowers
image: logo.png
description: Simple HTML based Demo with many layers
facts:
  - Layer groups
  - Object movement
  - Object rotation
priority: 1
jsfiddle:
  mapping:
    html: "index.html"
    js: "flowers.js"
    css: "flowers.css"
  resources:
    - $FSI_SERVER$/$FSI_CONTEXT$/viewer/applications/layers/js/fsilayers.js
  tags:
    - FSI
    - FSI Server
    - FSI Layers
    - NeptuneLabs
