overview:
  title: Flowers
  image: logo.png
  description: Simple HTML based Demo with many layers
  facts:
    - Layer groups
    - Object movement
    - Object rotation
  order: 1
schema: bootstrap-taupe
sample:
  fsi:
    layers: true
