overview:
  title: Living Layer
  image: logo.png
  description: Background Video with dynamic resolution image in front.
  facts:
    - HTML Video Layer
    - No custom JS
    - Reference Sizing
  order: 2
schema: bootstrap-taupe
sample:
  menu:
    data: clothing-menu.yml
  featured:
    data: clothing-featured.yml
  highlight: DEAL OF THE DAY
  footer:
    credits:
      photos:
        - author: Artem Bondarchuk
          link: https://unsplash.com/@artembondarchuk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
          platform: Unsplash
      viewer:
        link: https://www.neptunelabs.com/fsi-viewer/
  fsi:
    layers: true
  bootstrap:
    icons: true
